version: '3.8'


services:
  # TODO : review with install / restore / test db / ...
  psh.db:
    image: mysql:5.7-debian
    container_name: psh.db
    hostname: psh.db
    restart: always
    volumes:
      - psh_db_data:/var/lib/mysql
      - psh_db_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: prestashop_admin
      MYSQL_PASSWORD: prestashop_admin
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - psh_backend

  psh.cli.npm:
    # image: node:17.6-bullseye
    image: node:14.19-buster
    # image: node:16.15-buster # TOCHECK : force npm version to 7 ?
    container_name: psh.cli.npm
    hostname: psh.cli.npm
    user: ${HOST_ID}
    working_dir: /home/node/prestashop
    volumes:
      - ${INFRA_SRC_PSH}:/home/node/prestashop:rw
      - ${INFRA_CACHE_PATH}/npm:/.npm:rw
    networks:
      - psh_backend
    # This command should fix `Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch ...` problem
    command: >
      sh -c "echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && 
        sysctl -p"

  psh.app:
    build:
      context: ${INFRA_DOCKER_PATH}/src/
      dockerfile: ${INFRA_DOCKER_PATH}/src/Dockerfile.prestashop.7.4.dev
      args:
        - working_dir=/var/www/html
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    depends_on:
      proxy.letsencrypt:
        condition: service_started
      psh.db:
        condition: service_healthy
    container_name: psh.app
    hostname: psh.app
    extra_hosts:
      - "host.docker.internal:host-gateway" # necessary for xdebug reverse networking
    expose:
      - 80
      - 443
    # restart: always
    environment:
      # Proxy integration
      # VIRTUAL_HOST: ${PROXY_BASE_HOSTNAME}
      # HTTPS_METHOD: noredirect
      LETSENCRYPT_HOST: ${PROXY_BASE_HOSTNAME_LIST}
      COMPOSER_HOME: /tmp/composer
      # - COMPOSER_HOME=${INFRA_COMPOSER_HOME:-$HOME/.config/composer}
      # - COMPOSER_CACHE_DIR=${INFRA_COMPOSER_CACHE_DIR:-$HOME/.cache/composer}
    volumes:
      - ${INFRA_CACHE_PATH}/composer:/tmp/composer:rw
      - ${INFRA_SRC_PSH}:/var/www/html:delegated
      # TODO : review this volume usage once Prestashop ssl management properly configured.
      # cf. Dockerfile for consistency.
      - proxy_certs:/etc/nginx/certs
      - ${INFRA_ENV_PATH}/prestashop/php.ini:/usr/local/etc/php/conf.d/php-presta.ini:ro
      - ${INFRA_ENV_PATH}/prestashop/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ${INFRA_ENV_PATH}/xdebug/psh.app:/var/logs/xdebug:rw
    networks:
      - psh_backend
      - endpoints

volumes:
  psh_db_data:
    driver: local
  psh_db_init:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${INFRA_ENV_PATH}/prestashop/docker-entrypoint-initdb.d

networks:
  psh_backend:
    name: ${DOCKER_NETWORK}/psh.backend
    driver: bridge
