version: '3.8'

services:

  proxy.nginx:
    image: nginxproxy/nginx-proxy:1.0
    container_name: proxy.nginx
    volumes:
      # :point_up: rw is required due to specific docker image behavior
      - ${INFRA_ENV_PATH}/proxy/etc/nginx/conf.d:/etc/nginx/conf.d:rw
      - proxy_html:/usr/share/nginx/html
      - proxy_dhparam:/etc/nginx/dhparam
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_certs:/etc/nginx/certs
      - /run/docker.sock:/tmp/docker.sock:ro
    environment:
      - HTTPS_METHOD=noredirect
      # - DEBUG=true
    restart: always
    networks:
      - endpoints
    ports:
      - 80:80
      - 443:443

  proxy.letsencrypt:
    image: nginxproxy/acme-companion:2.2
    container_name: proxy.letsencrypt
    volumes:
      - proxy_html:/usr/share/nginx/html
      - proxy_dhparam:/etc/nginx/dhparam
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_certs:/etc/nginx/certs
      - /run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=proxy.nginx
      - DEFAULT_EMAIL=${PROXY_DEFAULT_EMAIL}
    restart: always
    depends_on:
      - proxy.nginx
    networks:
      - endpoints


volumes:
  proxy_certs:
    driver: local
  proxy_html:
    driver: local
  proxy_vhost:
    driver: local
    # TODO : review this usage for production & letsencrypt usage.
    driver_opts:
      o: bind
      type: none
      device: ${INFRA_ENV_PATH}/proxy/etc/nginx/vhost.d
  proxy_dhparam:
    driver: local
  # proxy_tmp:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ${INFRA_ENV_PATH}/proxy/tmp

